# Generated by Django 5.2.17 on 2026-09-18 13:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='ФИО')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Электронная почта')),
            ],
            options={
                'verbose_name': 'автор',
                'verbose_name_plural': 'авторы',
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('slug', models.SlugField(unique=True, verbose_name='Адрес')),
                ('description', models.TextField(verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
            ],
            options={
                'verbose_name': 'проект',
                'verbose_name_plural': 'проекты',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('slug', models.SlugField(verbose_name='Адрес')),
                ('summary', models.TextField(verbose_name='Краткое описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='docs.project', verbose_name='Проект')),
            ],
            options={
                'verbose_name': 'документ',
                'verbose_name_plural': 'документы',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Version',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(help_text='Например: 1.0 или 2.1', max_length=32, verbose_name='Номер версии')),
                ('content', models.TextField(help_text='Обычный текст; HTML не исполняется.', verbose_name='Содержимое')),
                ('change_note', models.CharField(max_length=255, verbose_name='Описание изменений')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('published', 'Опубликована')], default='draft', max_length=12, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('published_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Опубликована')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='versions', to='docs.author', verbose_name='Автор')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='versions', to='docs.document', verbose_name='Документ')),
            ],
            options={
                'verbose_name': 'версия',
                'verbose_name_plural': 'версии',
                'ordering': ['-published_at', '-pk'],
            },
        ),
        migrations.AddConstraint(
            model_name='document',
            constraint=models.UniqueConstraint(fields=('project', 'slug'), name='unique_document_slug'),
        ),
        migrations.AddConstraint(
            model_name='version',
            constraint=models.UniqueConstraint(fields=('document', 'number'), name='unique_version_number'),
        ),
        migrations.AddConstraint(
            model_name='version',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('published_at__isnull', True), ('status', 'draft')), models.Q(('published_at__isnull', False), ('status', 'published')), _connector='OR'), name='consistent_publication'),
        ),
    ]
